version: "3"

services:
  flarum:
    image: mondedie/flarum:stable
    container_name: flarum
    env_file:
      - .flarum.env
    ports:
      - "9003:8888"
    volumes:
      - /mnt/docker/flarum/assets:/flarum/app/public/assets
      - /mnt/docker/flarum/extensions:/flarum/app/extensions
      - /mnt/docker/flarum/nginx:/etc/nginx/conf.d
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.4
    container_name: mariadb-flarum
    env_file:
      - .flarum.env    
    environment:
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=flarum
    volumes:
      - /mnt/docker/mysql-flarum/db:/var/lib/mysql
